### ISSUE TITLE
Symfony YAML class

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#936]
@ulrichblock 

You gave me the dump to test:
https://github.com/easy-wi/developer/issues/923

Like:
```
query_enabled: true
disabled_commands:
    - disabledcommandhere
player_limit: -1
permissions:
    default: [bungeecord.command.server, bungeecord.command.list]
    admin: [bungeecord.command.alert, bungeecord.command.end, bungeecord.command.ip, bungeecord.command.reload]
timeout: 30000
query_port: 27045
online_mode: true
host: 87.xxx.xxx.xxx
servers:
    lobby: { motd: '&1Just another BungeeCord - Forced Host', address: 'localhost:25565', restricted: false }
listeners:
    - { query_port: 25577, motd: '&1Another Bungee server', tab_list: GLOBAL_PING, query_enabled: false, forced_hosts: { pvp.md-5.net: pvp }, ping_passthrough: false, default_server: lobby, bind_local_address: true, fallback_server: lobby, host: '0.0.0.0:25577', max_players: 1, tab_size: 60, force_default_server: false }
stats: 49a0b716-ef9a-48ab-98da-eace8e34c51d
ip_forward: false
groups:
    md_5: [admin]
connection_throttle: 4000
bind_local_address: true
```

But Symfony does the following:
```
query_enabled: true
disabled_commands:
    - disabledcommandhere
player_limit: -1
permissions:
    default: [bungeecord.command.server, bungeecord.command.list]
    admin: [bungeecord.command.alert, bungeecord.command.end, bungeecord.command.ip, bungeecord.command.reload]
timeout: 30000
query_port: '27045'
online_mode: true
host: '87.xxx.xxx.xxx'
servers:
    lobby: { motd: '&1Just another BungeeCord - Forced Host', address: 'localhost:25565', restricted: false }
listeners:
    - { query_port: '25577', motd: '&1Another Bungee server', tab_list: GLOBAL_PING, query_enabled: false, forced_hosts: { pvp.md-5.net: pvp }, ping_passthrough: false, default_server: lobby, bind_local_address: true, fallback_server: lobby, host: '0.0.0.0:25577', max_players: 1, tab_size: 60, force_default_server: false }
stats: 49a0b716-ef9a-48ab-98da-eace8e34c51d
ip_forward: false
groups:
    md_5: [admin]
connection_throttle: 4000
bind_local_address: true
```

The quotes are the problem again (at the host ip and query_port)...
Without them it works.
